version: "3"
services:
  api:
    container_name: vinopinionsapi-test
    image: ghcr.io/layla-oskar-schule/vinopinionsapi-staging:latest
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - vinopinionsapi-test-internal
      - server
  postgres:
    container_name: vinopinionsapi-test-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - vinopinionsapi-test-db-data:/var/lib/postgresql/data
    networks:
      - vinopinionsapi-test-internal
networks:
  server:
    external: true
  internal:
    internal: true
volumes:
  db-data:
