version: "3"
services:
  api:
    container_name: vinopinionsapi-test
    image: ghcr.io/layla-oskar-schule/vinopinionsapi-staging:latest
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - internal
      - server
  postgres:
    container_name: vinopinionsapi-test-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
  pgadmin:
    image: dpage/pgadmin4
    container_name: vinopinionsapi-test-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internal
      - server
networks:
  server:
    external: true
  internal:
    internal: true
volumes:
  db-data:
  pgadmin-data:
